# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dd83225a8b770bc3fb9cd07a1eb4fe1d339cb04b784e889f997ab16e474f45a56348401c64cf1f8ed6b10e870317935e5ba97775a19470df98115e6df37d5890

test:
  secret_key_base: c13b3e451267e127173f9f7e8baeb54b48aa3b16f2a2c1fc324776eaf6235a0166dd28b98dd4de3d235a0a82ce88365b9a4acc96d94d86573a330be199448c32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
